### ISSUE TITLE
Replace gulp with npm scripts

### ISSUE THREAD

**Issue by charwking** [charwking/cwking-api#12]
I think it would be cool to try using only npm scripts instead of gulp (or grunt). [Here's an article](http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt/) that talks about why, and [here's another one](http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/) that talks about how.

**Comment by AsmodeusXI** [comment]
SO HE SAYS RIGHT AFTER I ADD IT. :rage: 

Actually, I saw that first article not too long ago and it looked rather intriguing. Having already been swept up in the "latest craze of task-runners" I didn't think too much about it, but it'd be interesting to explore another methodology.
