### ISSUE TITLE
Select input validation technology

### ISSUE THREAD

**Issue by cwkingjr** [charwking/cwking-api#2]
Project needs to select a database integration technology that ensures very good input validation. This is usually done through a combination of data-type validators (integer, regex, string) via a form validation toolset, ORM translation, etc.

**Comment by cwkingjr** [comment]
MEAN's mongoose has some built in validation code and the ability to create custom validators.

Project Nodal (http://www.nodaljs.com/) is an API framework modeled after some of the good parts of Django and Rails, and has some input validation capabilities.

I'm still exploring.

**Comment by charwking** [comment]
Our database options are MySQL, Postgres, or anything we decide to install and manage ourselves (e.g. Mongo)

**Comment by charwking** [comment]
[Sequelize](http://docs.sequelizejs.com/en/v3/) definitely looks to be [the most popular](https://npmcompare.com/compare/bookshelf,objection,orm,sequelize,sql-bricks). Does this choice fulfill this issue @cwkingjr?

**Comment by cwkingjr** [comment]
Yes
