### ISSUE TITLE
Determine folder layout preferences

### ISSUE THREAD

**Issue by cwkingjr** [charwking/cwking-api#22]
Will this back end application be laid out like this:

controllers/authentication-controller.js
services/authentication-service.js

Like this:

auth/authentication-service.js
auth/authentication-controller.js

Or some other way? @charwking, would you mind building out a few scaffolding folders showing where you want things to go?

**Comment by cwkingjr** [comment]
@charwking Please also include the node file naming convention. E.g., would it be authentication.controller.js or authentication-controller.js?

**Comment by charwking** [comment]
See PR #23.

I prefer grouping things by feature, but it appears that grouping by function is going to provide some nice optimizations. If my OCD gets to me, or the functional grouping proves unwieldy, I may come back around and change this at a later time.
