### ISSUE TITLE
Don't track npm-debug.log in repo

### ISSUE THREAD

**Issue by cwkingjr** [charwking/cwking-api#7]
Mod .gitignore to fix this.

**Comment by charwking** [comment]
Never done it, but we could consider ignoring some things by each of us [configuring our own global gitignore file](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore).

**Comment by charwking** [comment]
Thinking about it a little more, we should probably add files that are generated by this project (like the *.log files) to the "local" `.gitignore`, and files that are generated by our code editors, OSes, etc (like *.swp, .DS_Store) in our global gitignore files. So, continue as you were :smile:
